[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules','lib']
test = 'test-foundry'

[fuzz]
runs = 1000

remappings = ["forge-std/=lib/forge-std/src/","@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config